### ISSUE TITLE
[setting] 목 서버를 이용한 목 API 제작

### ISSUE THREAD

**Issue by nakyeonko3** [FC-DEV-FinalProject/final-fe-team4#117]
### 📄 구성 변경 상세 내용

백엔드 API 명세서를 바탕으로 목API 제작

**Comment by sjgaru-dev** [comment]
빌드된 도커 이미지를 RDS가 아닌 다른 mysql DB 에 연결시켜서 
또 다른 백엔드 서버로 구동 - https://mock.popomance.kr/ 

beecepton, mockoon, mockserver, postman, msw 등 다양한 툴로 시도하였는데
mock api 자체가 api 가 나오지 않아 필요한 건데
이미 api가 나와있다면 목서버가 아니라 해당 api 를 사용하면 되는 것 아닌가 로 근본적인 의문이 들어 
백엔드에 문의하여 다른 서버를 구축하는 것으로 해결하였습니다.
