### ISSUE TITLE
[docs] 툴팁이 들어갈 위치를 캡처해서 올려주세여

### ISSUE THREAD

**Issue by nakyeonko3** [FC-DEV-FinalProject/final-fe-team4#164]
### 📄 문서 업데이트 상세 내용

# 피그마나 실제 화면에 툴팁이 들어갈 위치를 캡처해서 올려주시면 됩니다.

**Comment by nakyeonko3** [comment]
1. 그리뷰 토글 버튼
![image](https://github.com/user-attachments/assets/a7209193-e777-4949-b2a0-3b010acc0ac1)


2. 하단 재생성 버튼
![image](https://github.com/user-attachments/assets/f063fd6a-8fc1-41b6-bcd4-e02d7b0847a9)

**Comment by dhkim511** [comment]
![스크린샷 2024-11-22 105058](https://github.com/user-attachments/assets/cd52eff4-5a3a-491d-ab17-0da7c297188c)

**Comment by dhkim511** [comment]
![스크린샷 2024-11-22 105139](https://github.com/user-attachments/assets/6cbbebb1-213c-4480-b9db-86bdc1877a4b)
![스크린샷 2024-11-22 105144](https://github.com/user-attachments/assets/12e76451-5c10-44d9-8245-42af6862f2fb)

**Comment by dhkim511** [comment]
![image](https://github.com/user-attachments/assets/38f8b2ed-4427-4d2b-a4b2-112631e89e90)
