### ISSUE TITLE
[feat] 다중탭 5개로 제한

### ISSUE THREAD

**Issue by dyeongg** [FC-DEV-FinalProject/final-fe-team4#223]
### 📄 설명

<img width="287" alt="스크린샷 2024-11-29 오전 10 45 02" src="https://github.com/user-attachments/assets/91bf273a-9f66-4ec7-829d-63999f667237">

프로젝트가 너무 많이 열리지 않도록 최대 5개로 제한

**Comment by miniseung** [comment]
음 이게 아직 api가연결이 안되서 로컬에 쌓인게 많아서 그런데 로컬스토리지 지우면 탭 사라집니다 ㅠㅠ 추후 닫기 버튼에 로컬스토리지 지우는 기능 추가하면 될거 같아요
