### ISSUE TITLE
[setting] 도메인 후보 정하기 

### ISSUE THREAD

**Issue by nakyeonko3** [FC-DEV-FinalProject/final-fe-team4#45]
### 📄 구성 변경 상세 내용

https://hosting.cafe24.com/?controller=new_domain_search
도메인 후보 정하기

**Comment by sjgaru-dev** [comment]
https://domain.gabia.com/regist/regist_step1.php
https://hosting.kr/domain/
https://kr.godaddy.com/domainsearch/

도메인 판매 사이트마다 가격이 달라 .kr 이 만원 미만인 곳도 있어서 
일단 하고 싶은거 다 나열하고 가격에 맞춰서 정하는 것도 방법일 것 같습니다.

**Comment by nakyeonko3** [comment]
> https://domain.gabia.com/regist/regist_step1.php
> https://hosting.kr/domain/
> https://kr.godaddy.com/domains
> 
> 도메인 판매 사이트마다 가격이 달라 .kr 이 만원 미만인 곳도 있어서 
> 일단 하고 싶은거 다 나열하고 가격에 맞춰서 정하는 것도 방법일 것 같습니다.

맞습니다. 일단 그냥 하고 싶은거 다 나열 해두면 좋을것 같습니다

**Comment by dyeongg** [comment]
<img width="719" alt="스크린샷 2024-11-07 오후 12 29 05" src="https://github.com/user-attachments/assets/9c69d189-d65b-4153-a2d7-59ce12e43138">

이런것도 괜찮아 보입니다
1년 10000원 미만으로 하면 좋을 것 같네요

**Comment by nakyeonko3** [comment]
![Image](https://github.com/user-attachments/assets/1e8cb742-c899-442c-8292-4b01ecfae6a8)

**Comment by nakyeonko3** [comment]
![Image](https://github.com/user-attachments/assets/4e463147-c938-445b-9cb3-eb5466364c74)
깃허브 프로계정이라서 1년 무료네요.

**Comment by sjgaru-dev** [comment]
popomance.kr 확정
