### ISSUE TITLE
[feat] 메인 홈 화면 -  상단 팝업

### ISSUE THREAD

**Issue by nakyeonko3** [FC-DEV-FinalProject/final-fe-team4#95]
### 📄 설명

메인 홈 화면 상단 팝업 제작

![image](https://github.com/user-attachments/assets/19fb4ddd-5e18-4a51-8070-daf46f92c9f5)

**Comment by miniseung** [comment]
홈 화면 컨포넌트화해서 쪼개서 나누면 좋을거 같습니다

**Comment by nakyeonko3** [comment]
그럼 이슈를 분할 하겠습니다.

**Comment by nakyeonko3** [comment]
![image](https://github.com/user-attachments/assets/19fb4ddd-5e18-4a51-8070-daf46f92c9f5)
